// This file was autogenerated by app/libs/closurelibrary/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/app.js', ['fiahfy.sample.App'], ['fiahfy.mod.application.Application', 'fiahfy.mod.math.Math', 'fiahfy.mod.scene.Scene', 'fiahfy.mod.scene.shape.Rectangle', 'fiahfy.mod.stage.Stage']);
goog.addDependency('../../../../js/mod/application.js', ['fiahfy.mod.application.Application'], ['fiahfy.mod.stage.Stage']);
goog.addDependency('../../../../js/mod/base.js', ['fiahfy.mod'], []);
goog.addDependency('../../../../js/mod/geometory.js', ['fiahfy.mod.geometory.Dimension', 'fiahfy.mod.geometory.Point'], []);
goog.addDependency('../../../../js/mod/math.js', ['fiahfy.mod.math.Math'], []);
goog.addDependency('../../../../js/mod/scene.js', ['fiahfy.mod.scene.Scene', 'fiahfy.mod.scene.shape.Rectangle'], ['fiahfy.mod.geometory.Dimension', 'fiahfy.mod.geometory.Point']);
goog.addDependency('../../../../js/mod/stage.js', ['fiahfy.mod.stage.Stage'], ['fiahfy.mod.scene.Scene']);
