// This file was autogenerated by app/libs/closurelibrary/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/app.js', ['com.blogspot.fiahfy.App'], ['com.blogspot.fiahfy', 'com.blogspot.fiahfy.Math']);
goog.addDependency('../../../../js/base.js', ['com.blogspot.fiahfy'], []);
goog.addDependency('../../../../js/math.js', ['com.blogspot.fiahfy.Math'], []);
